platforum_project/forum/urls.py
from django.urls import path
from .views import create_forum, index, sub_category_view, add_topic, topic_view, update_message, delete_message, \
    personal_messaging, conversation_view, update_message_conversation, delete_message_conversation, profile_forum, \
    signup_forum, members_list_view, pin_topic, display_members, member_status_view, member_view, builder_view, \
    delete_category_view, delete_subcategory_view, update_category_view, update_subcategory_view, start_conversation, \
    index_admin_view, notifications_view, delete_notifications, update_topic, delete_topic_view, query_view, \
    add_sub_category, like_unlike_view

app_name = "forum"
urlpatterns = [
    path('create-forum/', create_forum, name="create-forum"),
    path('<str:slug_forum>/<int:pk_forum>/signup/', signup_forum, name="signup"),
    path('<str:slug_forum>/<int:pk_forum>/index/', index, name="index"),
    path('<str:slug_forum>/<int:pk_forum>/sub-category/<int:pk>/<str:slug_sub_category>', sub_category_view,
         name="sub-category"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk>/<str:slug_sub_category>/add/', add_topic, name="add-topic"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk>/<str:slug_sub_category>/<int:pk_topic>/<str:slug_topic>/',
         topic_view,
         name="topic"),
    path(
        '<str:slug_forum>/<int:pk_forum>/<int:pk>/<str:slug_sub_category>/<int:pk_topic>/<str:slug_topic>/<int:pk_message>/',
        update_message,
        name="update-message"),
    path('<int:pk_forum>/delete-message/<int:pk_topic>/<int:pk_message>/', delete_message, name="delete-message"),
    path('<int:pk_forum>/<int:pk_message>/like', like_unlike_view, name="like"),
    path('<str:slug_forum>/<int:pk_forum>/private-messaging/', personal_messaging, name="private-messaging"),
    path('<str:slug_forum>/<int:pk_forum>/private-messaging/<str:slug_conversation>/<int:pk_conversation>/',
         conversation_view,
         name="conversation"),
    path('<str:slug_forum>/<int:pk_forum>/start-conversation/<int:pk_member>/', start_conversation,
         name="start-conversation"),
    path(
        '<str:slug_forum>/<int:pk_forum>/update-message/<str:slug_conversation>/<int:pk_conversation>/<int:pk_message>',
        update_message_conversation,
        name="update-message-conversation"),
    path('<int:pk_forum>/delete-message-conversation/<int:pk_conversation>/<int:pk_message>/',
         delete_message_conversation,
         name="delete-message-conversation"),
    path('<str:slug_forum>/<int:pk_forum>/profile/', profile_forum, name="profile"),
    path('<str:slug_forum>/<int:pk_forum>/members-list/', members_list_view, name="members-list"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk_member>/', member_view, name="member"),
    path("<str:slug_forum>/<int:pk_forum>/notifications/", notifications_view, name="alerts"),
    path('<int:pk_forum>/delete-notifications/', delete_notifications, name="delete-alerts"),
    path('<str:slug_forum>/<int:pk_forum>/query', query_view, name="query"),

    # Admin Part
    path('<str:slug_forum>/<int:pk_forum>/admin/index', index_admin_view, name="admin-index"),
    path('<int:pk_forum>/<int:pk_topic>/pin/', pin_topic, name="pin"),
    path('<str:slug_forum>/<int:pk_forum>/admin/members/', display_members, name="admin-members"),
    path('<int:pk_forum>/<int:pk_member>/admin/member-status/', member_status_view, name="admin-member-status"),
    path('<str:slug_forum>/<int:pk_forum>/admin/builder/', builder_view, name="builder"),
    path('<int:pk_forum>/<int:pk_category>/admin/delete-category/', delete_category_view, name="delete-category-admin"),
    path('<int:pk_forum>/<int:pk_subcategory>/admin/delete-subcategory/', delete_subcategory_view,
         name="delete-subcategory-admin"),
    path('<str:slug_forum>/<int:pk_forum>/admin/update-category/<int:pk_category>/', update_category_view,
         name="admin-update-category"),
    path('<str:slug_forum>/<int:pk_forum>/admin/update-subcategory/<int:pk_subcategory>/', update_subcategory_view,
         name="admin-update-subcategory"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk_category>/admin/add-subcategory/', add_sub_category,
         name="admin-add-sub-category"),
    path('<str:slug_forum>/<int:pk_forum>/admin/update-topic/<int:pk_topic>/', update_topic, name="admin-update-topic"),
    path('<int:pk_forum>/admin/delete-topic/<int:pk_topic>/', delete_topic_view, name="admin-delete-topic"),
]

platforum_project/platforum_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('account/', include('account.urls')),
    path('forum/', include('forum.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sav/', include('sav.urls')),
]

if settings.ENV != "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platforum_project/sav/urls.py
from django.urls import path
from .views import contact_view, legal_view


app_name = "sav"
urlpatterns = [
    path('contact/', contact_view, name="contact"),
    path('legal/', legal_view, name="legal")
    ]

platforum_project/forum/models/content.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone

from forum.default_data.messages import welcome_message
from .interactions import Like


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name="Nom")
    forum = models.ForeignKey(to="Forum", on_delete=models.CASCADE, verbose_name="Forum")
    index = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Catégorie"
        ordering = ["index"]

    def __str__(self):
        return f"{self.name} - {self.forum.name}"

    @classmethod
    def create_test_category(cls, forum):
        return cls.objects.create(name="Catégorie Test", forum=forum)

    @property
    def get_sub_categories(self):
        return SubCategory.objects.filter(category=self)


class SubCategory(models.Model):
    name = models.CharField(max_length=50, verbose_name="Sous catégorie")
    slug = models.SlugField(blank=True)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name="Catégorie",
                                 related_name="subcategories")
    index = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name} - {self.category}"

    @classmethod
    def create_test_subcategory(cls, category):
        return cls.objects.create(name="Sous catégorie Test", category=category)

    @property
    def number_of_messages(self):
        return Message.objects.filter(topic__sub_category=self).count()

    @property
    def last_topic_commented(self):
        try:
            return Message.objects.filter(topic__sub_category=self).last().topic.title
        except AttributeError:
            return "Pas encore de sujet, lance toi ! :)"

    class Meta:
        verbose_name = "Sous catégorie"
        ordering = ["index"]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Topic(models.Model):
    title = models.CharField(max_length=100, verbose_name="Titre")
    slug = models.SlugField(blank=True)
    # Système d'alerte si sub_category est null
    sub_category = models.ForeignKey(to=SubCategory, on_delete=models.CASCADE)
    # Si le modérateur souhaite clôturer le sujet sans le supprimer
    closed = models.BooleanField(default=False, verbose_name="Clôturé")
    account = models.ForeignKey(to="ForumAccount", verbose_name="Auteur", on_delete=models.SET_NULL, null=True)
    creation = models.DateTimeField(auto_now_add=True, verbose_name="Date de publication")
    pin = models.BooleanField(default=False, verbose_name="Epinglé")
    last_activity = models.DateTimeField(auto_now=True, verbose_name="Activité récente")

    class Meta:
        verbose_name = "Sujet"
        ordering = ['-last_activity']

    def __str__(self):
        return f"{self.title} - {self.account.user.username} - {self.sub_category.category.forum}"

    def pin_topic(self):
        self.pin = True
        self.save(update_fields=["pin"])
        return self

    def unpin_topic(self):
        self.pin = False
        self.save(update_fields=["pin"])
        return self

    @property
    def author(self):
        return self.account.user.username if self.account else "Utilisateur banni"

    @property
    def number_of_messages(self):
        return Message.objects.filter(topic=self).count()

    @property
    def last_message(self):
        return Message.objects.filter(topic=self).last().account.user.username

    @classmethod
    def create_topic_test(cls, sub_category, account):
        return cls.objects.create(title="Bienvenu(e)", sub_category=sub_category, account=account)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        sub_category = self.sub_category
        forum = sub_category.category.forum
        return reverse("forum:topic", kwargs={
            "slug_forum": forum.slug,
            "pk_forum": forum.pk,
            "pk": sub_category.pk,
            "slug_sub_category": sub_category.slug,
            "pk_topic": self.pk,
            "slug_topic": self.slug
        })


class Message(models.Model):
    message = models.TextField(verbose_name="Message")
    account = models.ForeignKey(to="ForumAccount", verbose_name="Auteur", on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(to=Topic, verbose_name="Sujet", on_delete=models.CASCADE, null=True, blank=True)
    conversation = models.ForeignKey(to="Conversation", on_delete=models.CASCADE,
                                     verbose_name="Messagerie Personnel", null=True, blank=True)
    personal = models.BooleanField(verbose_name="Personnel", default=False)
    creation = models.DateTimeField(auto_now_add=True, verbose_name="Date de publication")
    update = models.DateTimeField(auto_now=True, verbose_name="Modifié le", null=True)
    update_counter = models.IntegerField(default=0, verbose_name="Nombre de maj")

    @property
    def like_counter(self):
        return Like.objects.filter(message=self).count()

    @property
    def author(self):
        return self.account.user.username if self.account else "Utilisateur banni"

    def __str__(self):
        return f"{self.account.user.username} - {self.creation}"

    @classmethod
    def message_test(cls, topic, account):
        return cls.objects.create(message=welcome_message(account), account=account, topic=topic)

    def save(self, *args, **kwargs):
        """
            Overrides the save method to update message counters and topic activity.

            This method first checks if the Message object already exists in the database. If it does, it increments the
            message's update counter. If the message is new and is not marked as personal, it updates the 'last_activity'
            field of the associated topic to the current time. Finally, it calls the superclass's save method to handle
            the actual saving of the Message object.

            Args:
                *args: Variable length argument list.
                **kwargs: Arbitrary keyword arguments.

            Side effects:
                - Increments the update counter of an existing message.
                - Updates the 'last_activity' field of the associated topic for new, non-personal messages.
                - Saves the Message object to the database.
            """
        existing_message = Message.objects.filter(pk=self.pk).exists()
        if existing_message:
            self.update_counter += 1
        if not existing_message and not self.personal:
            self.topic.last_activity = timezone.now()
            self.topic.save(update_fields=["last_activity"])
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['creation']


class Conversation(models.Model):
    account = models.ForeignKey(to="ForumAccount", on_delete=models.CASCADE, verbose_name="Utilisateur",
                                related_name="messaging")
    contacts = models.ManyToManyField(to="ForumAccount", verbose_name="Contacts")
    forum = models.ForeignKey(to="Forum", on_delete=models.CASCADE, verbose_name="Forum")
    subject = models.CharField(max_length=50, verbose_name="Sujet")
    slug = models.SlugField(blank=True)

    def __str__(self):
        return f"Discussion de {self.account.user.username} - {self.forum}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.subject)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Conversation"

    @property
    def number_of_messages(self):
        return Message.objects.filter(conversation=self).count()

    @property
    def last_message(self):
        return Message.objects.filter(conversation=self).last().account.user.username

    def get_absolute_url(self):
        return reverse("forum:conversation", kwargs={"slug_forum": self.forum.slug,
                                                     "pk_forum": self.forum.pk,
                                                     "slug_conversation": self.slug,
                                                     "pk_conversation": self.pk})

platforum_project/forum/models/interactions.py
from django.db import models


class Notification(models.Model):
    account = models.ForeignKey(to="ForumAccount", on_delete=models.CASCADE, verbose_name="Compte")
    message = models.CharField(max_length=200)

    @classmethod
    def notify_member_if_message_posted_in_topic(cls, topic, account):
        if topic.account != account:
            topic.account.notification_counter += 1
            topic.account.save(update_fields=["notification_counter"])
            return cls.objects.create(account=topic.account,
                                      message=f"Nouveau message posté par {account.user.username} dans {topic.title}")

    @classmethod
    def notify_member_if_message_posted_in_conversation(cls, conversation, account):
        if conversation.account != account:
            conversation.account.notification_counter += 1
            conversation.account.save(update_fields=["notification_counter"])
            return cls.objects.create(account=conversation.account,
                                      message=f"Boite personnelle : Nouveau message posté par {account.user.username} "
                                              f"dans {conversation.subject}")


class Like(models.Model):
    message = models.ForeignKey(to="Message", on_delete=models.CASCADE)
    liker = models.ForeignKey(to="ForumAccount", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.liker} - {self.message}"

    @classmethod
    def like_unlike(cls, liker, message):
        like, created = cls.objects.get_or_create(message=message, liker=liker)
        if not created:
            like.delete()

platforum_project/forum/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .forms import CreateForumForm
from .default_data.default_forum_data import create_forum_with_data


@login_required
def create_forum(request):
    user = request.user
    if request.method == "POST":
        form = CreateForumForm(request.POST)
        if form.is_valid():
            create_forum_with_data(form, user)

    form = CreateForumForm()
    return render(request, "forum/create-forum.html", context={"form": form})

platforum_project/forum/views/creation.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from forum.forms import CreateForumForm
from forum.default_data.default_forum_data import create_forum_with_data


@login_required
def create_forum(request):
    """
        Handles the creation of a new forum.

        This view, accessible only to logged-in users, provides a form for creating a new forum. Upon submission of the
        form with valid data (POST request), a new forum is created using the 'create_forum_with_data' function with the
        logged-in user as the forum master. The user is then redirected to the newly created forum. If accessed via a GET
        request, the form for creating a new forum is displayed.

        Args:
            request: The HTTP request object, either GET for displaying the form or POST for submitting form data.

        Returns:
            HttpResponse: Renders the forum creation page with the form or redirects to the new forum's page after creation.
        """
    user = request.user
    if request.method == "POST":
        form = CreateForumForm(request.POST, request.FILES)
        if form.is_valid():
            forum = create_forum_with_data(form, user)
            return redirect("forum:index", slug_forum=forum.slug, pk_forum=forum.pk)
    else:
        form = CreateForumForm()
    return render(request, "creation/create-forum.html", context={"form": form})

platforum_project/forum/templates/forum/index.html
{% extends "base_forum.html" %}
{% load static %}

{% block title %}Forum de {{ forum.forum_master.username }}{% endblock %}

{% block head %}
<hr>
<p>{{ forum.description }}</p>
{% endblock %}
{% block body %}


{% for category in categories %}
<div class="container shadow-lg rounded border p-5 mb-5">


    <div class="card text-center">
        <div class="card-header row fw-bold mx-0" style="background-color: rgba(136, 204, 136);">
            <div class="col-6">{{ category.name }}</div>
            <div class="col-6">Dernier sujet commenté</div>
        </div>

        {% for subcategory in category.subcategories.all %}
        <div class="row border-bottom p-2 mx-0">
            <div class="d-flex justify-content-between align-items-center">
                <div class="col-6">
                    <a class="cat-link"
                       href="{% url 'forum:sub-category' slug_forum=forum.slug pk_forum=forum.pk pk=subcategory.pk slug_sub_category=subcategory.slug %}">
                        <strong>{{ subcategory.name }}</strong>
                    </a><br>
                    <span class="badge bg-success">Sujets : {{ subcategory.topic_set.all.count }}</span><br>
                    <span class="badge bg-secondary">Messages : {{ subcategory.number_of_messages }}</span>
                </div>


                <div class="col-6">{{ subcategory.last_topic_commented }}</div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endfor %}
{% endblock %}

platforum_project/forum/templates/forum/member.html
{% extends "base_forum.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}{{ member.user.username }}{% endblock %}

{% block body %}


<div class="container shadow-lg rounded border p-5 mb-5">
    <div class="row mb-2">
        <div class="col-3"><a href="{% url 'forum:members-list' slug_forum=forum.slug pk_forum=forum.pk %}"><img src="{% static 'assets/return.png' %}" height="40" width="auto"></a></div>
    </div>
    <div class="row text-center justify-content-center">
        <div class="col-6">
            <h2 class="mb-2">Compte de <span style="color: rgba(25, 135, 84);">{{ member.user.username }}</span></h2>
            <h5 class="mb-5">A rejoint le forum le <span style="color: blue;">{{ member.joined }}</span></h5>
            <img src="{{ member.thumbnail_url }}" width="100" height="auto" class="rounded mb-5">

            <!-- Admin -->
            {% if account.forum_master %}
            {% if not member.forum_master %}
            {% if member.active %}
            <form method="post" class="mb-5" action="{% url 'forum:admin-member-status' pk_forum=forum.pk pk_member=member.pk %}">
                {% csrf_token %}
                <input type="hidden" name="redirect" value="member-view">
                <input type="submit" value="Actif" class="btn btn-success">
            </form>
            {% else %}
            <form method="post" action="{% url 'forum:admin-member-status' pk_forum=forum.pk pk_member=member.pk %}">
                {% csrf_token %}
                <input type="hidden" name="redirect" value="member-view">
                <input type="submit" value="Désactivé" class="btn btn-danger">
            </form>
            {% endif %}
            {% endif %}
            {% endif %}

            {% if member != account %}
            <form action="{% url 'forum:start-conversation' slug_forum=forum.slug pk_forum=forum.pk pk_member=member.pk %}">
                {% csrf_token %}
                <input type="submit" value="MP" class="btn btn-success">
            </form>
            {% endif %}

        </div>
    </div>


</div>

<div class="container shadow-lg rounded border p-5 mb-5">
    <div class="row text-center justify-content-center">
        <h2>Badges</h2>
        <div class="col-6 justify-content-center d-flex">
            {% if account.badges %}
            {% for badge in account.badges.all %}
            <div data-bs-toggle="tooltip" data-bs-placement="top"
                    data-bs-title="{{ badge.description }}">
                <img src="{{ badge.thumbnail.url }}" width="80" height="auto" class="mb-5 circle">
            </div>

            {% endfor %}
            {% endif %}
        </div>

    </div>
</div>

<div class="container shadow-lg rounded border p-5 mb-5">
    <div class="row text-center justify-content-center">
        <h2>Dernières contributions</h2>
        <div class="col-6">
            {% if messages %}
            <div class="list-group">
                {% for message in messages %}
                <a href="{% url 'forum:topic' slug_forum=forum.slug pk_forum=forum.pk pk=message.topic.sub_category.pk slug_sub_category=message.topic.sub_category.slug pk_topic=message.topic.pk slug_topic=message.topic.slug %}"
                   class="list-group-item list-group-item-action list-group-item-success">Dans {{ message.topic.title }}
                    le {{ message.creation }}</a>
                {% endfor %}
            </div>
            {% else %}
            <h6>{{ member.user.username }} n'a pas encore posté de message.</h6>
            {% endif %}
        </div>

    </div>
</div>

{% endblock %}

platforum_project/forum/templates/forum/members-list.html
{% extends "base_forum.html" %}
{% load static %}

{% block title %}Liste des Membres {{ forum.name }}{% endblock %}

{% block body %}

<div class="container shadow-lg rounded border p-5">
    <div class="row mb-2">
        <div class="col-3"><a href="{% url 'forum:index' slug_forum=forum.slug pk_forum=forum.pk %}"><img
                src="{% static 'assets/return.png' %}" height="40" width="auto"></a></div>
    </div>
    <div class="row text-center">
        <h2 class="mb-5">Liste des membres</h2>
    </div>


        <div class="row mb-5">
        <div class="col-lg-4 col-md-12">

                        <form role="search" class="d-flex">
        <input type="search" placeholder="Rechercher un membre" aria-label="Rechercher" name="search" class="form-control">
        <button type="submit" class="btn btn-success ms-2">Rechercher</button>
    </form>

        </div>

    </div>

    <div class="row text-center">
        <div class="col">
            <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Avatar</th>
                    <th scope="col">Membre</th>
                    <th scope="col">A rejoint</th>
                    <th scope="col">Messages</th>
                    <th scope="col">Badges</th>
                </tr>
                </thead>
                {% for member in members %}
                <tbody>
                <tr>
                    <td><img src="{{ member.thumbnail_url }}" width="auto" height="60"></td>
                    <th scope="row"><a class="name-list"
                                       href="{% url 'forum:member' slug_forum=forum.slug pk_forum=forum.pk pk_member=member.pk %}">{{ member.user.username }}</a></th>
                    <td>{{ member.joined }}</td>
                    <td>{{ member.messages_count }}</td>
                    <td class="d-flex justify-content-center align-items-center">{% if member.badges.all.count > 0 %}
            {% for badge in member.badges.all %}
            <div data-bs-toggle="tooltip" data-bs-placement="top"
                    data-bs-title="{{ badge.description }}">
                <img src="{{ badge.thumbnail.url }}" width="40" height="auto" class="mb-5 circle">
            </div>

            {% endfor %}
            {% endif %}</td>
                </tr>
                </tbody>
                {% endfor %}
            </table>
            </div>
        </div>


    </div>

</div>


{% endblock %}

platforum_project/forum/templates/forum/topic.html
{% extends "base_forum.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}{{ topic.title }}{% endblock %}

{% block body %}

<div class="container p-5 mb-4">
    <div class="row justify-content-between">
        <div class="col-4 shadow-lg">
            <h2>Sujet</h2>
            <h3 style="color: green;">{{ topic.title }}</h3>
            <a href="{% url 'forum:sub-category' slug_forum=forum.slug pk_forum=forum.pk pk=sub_category.pk slug_sub_category=sub_category.slug %}"><img
                    src="{% static 'assets/return.png' %}" height="40" width="auto"></a>
        </div>
        {% if request.user == forum.forum_master %}
        <div class="col-4 shadow-lg">
            <a href="{% url 'forum:admin-update-topic' slug_forum=forum.slug pk_forum=forum.pk pk_topic=topic.pk %}"
               class="btn btn-danger">Modifier le sujet</a>
        </div>
        {% endif %}
    </div>

</div>


<div class="container rounded p-5 mb-5 border shadow-lg">

    {% for message in page_obj %}


    <div class="card text-center shadow-lg mb-3">
        <div class="card-header" style="background-color: rgba(136, 204, 136);">

            Par <a class="name-link" href="{{ message.account.get_absolute_url }}">{{ message.account.user.username }}</a> <img class="rounded" src="{{ message.account.thumbnail_url }}" height="50" width="auto">


        </div>
        <div class="card-body">
            <div class="d-flex justify-content-end">

                {% if account.active %}
                <form action="{% url 'forum:like' pk_forum=forum.pk pk_message=message.pk %}" method="post">
                    {% csrf_token %}
                    <input type="image" src="{% static 'assets/like.png' %}" class="circle" height="40" width="auto">
                </form>
                {{ message.like_counter }}
                {% endif %}


                {% if request.user == message.account.user and account.active or request.user == forum.forum_master %}
                <a data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Modifier"
                   href="{% url 'forum:update-message' slug_forum=forum.slug pk_forum=forum.pk pk=sub_category.pk slug_sub_category=sub_category.slug pk_topic=topic.pk slug_topic=topic.slug pk_message=message.pk %}"><img
                        class="rounded" src="{% static 'assets/update.png' %}" height="40" width="auto"></a>

                <!-- Button trigger modal -->
                <button type="button" class="btn-close" data-bs-toggle="modal"
                        data-bs-target="#deletemodal{{ message.pk }}">
                </button>

                <!-- Modal -->
                <div class="modal fade" id="deletemodal{{ message.pk }}" tabindex="-1"
                     aria-labelledby="Delete{{ message.pk }}"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="Delete{{ message.pk }}">Supprimer le message</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Cette action est irréversible
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-success" data-bs-dismiss="modal">Retour</button>
                                <form method="post"
                                      action="{% url 'forum:delete-message' pk_forum=forum.pk pk_topic=topic.pk pk_message=message.pk %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Confirmer</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Enf of Modal -->

                {% endif %}

            </div>
            {{ message.message|safe }}

        </div>
        <div class="card-footer text-body-secondary">
            Le {{ message.creation }}
            {% if message.update_counter > 0 %}
            <i>Modifié le {{ message.update }}</i>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    <!-- Pagination -->
    <div class="row mt-5">

        <nav aria-label="Page navigation example">
            <ul class="pagination">

                {% if page_obj.has_previous %}
                <li><a href="?page=1" class="page-link">&laquo; Début</a></li>
                <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Précédent</a></li>
                {% endif %}


                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="page-link">Suivant</a></li>
                <li><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">Fin &raquo;</a></li>
                {% endif %}

            </ul>
        </nav>
        <strong>Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.</strong>


    </div>

</div>
{% if account %}
{% if account.active %}
<!-- Le formulaire pour répondre -->
<div class="container rounded p-5 mb-5 border shadow-lg">

    <div class="row">
        <div class="col-12 text-center">
            <h3>Réponse au sujet : <span style="color: rgba(25, 135, 84);">{{ topic.title }}</span></h3>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-12">
            <form method="post">
                {% csrf_token %}
                {{ form.media }}
                <div class="text-center">
                    {{ form|crispy }}

                    <input type="submit" value="Soumettre" class="btn btn-success">
                </div>
            </form>
        </div>

    </div>
    <div class="row" style="color: red;">
        {% if form.errors %}

        {{ form.errors }}

        {% endif %}

    </div>

</div>
{% endif %}
{% endif %}
{% endblock %}