platforum_project/account/urls.py
from django.urls import path
from .views import signup, LoginUser, logout_view, UserChangePassword, UserPasswordDone, UserResetPassword, \
    UserResetDone, UserResetConfirm, UserResetComplete, profile_view, activate

app_name = "account"
urlpatterns = [
    path('signup/', signup, name="signup"),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('login/', LoginUser.as_view(), name="login"),
    path('logout/', logout_view, name="logout"),
    path('change-password/', UserChangePassword.as_view(), name="change-password"),
    path('password-done/', UserPasswordDone.as_view(), name="password-done"),
    path('password-reset/', UserResetPassword.as_view(), name="password-reset"),
    path('password-reset-done/', UserResetDone.as_view(), name="reset-done"),
    path('password-reset-confirm/<str:uidb64>/<str:token>/', UserResetConfirm.as_view(), name="reset-confirm"),
    path('reset-complete/', UserResetComplete.as_view(), name="reset-complete"),
    path('profile/', profile_view, name="profile"),
]

platforum_project/forum/urls.py
from django.urls import path
from .views import create_forum, index, sub_category_view, add_topic, topic_view, update_message, delete_message, \
    personal_messaging, conversation_view, update_message_conversation, delete_message_conversation, profile_forum, \
    signup_forum, members_list_view, pin_topic, display_members, member_status_view, member_view, builder_view, \
    delete_category_view, delete_subcategory_view, update_category_view, update_subcategory_view, start_conversation, \
    index_admin_view, notifications_view, delete_notifications, update_topic, delete_topic_view, query_view, \
    add_sub_category, like_unlike_view

app_name = "forum"
urlpatterns = [
    path('create-forum/', create_forum, name="create-forum"),
    path('<str:slug_forum>/<int:pk_forum>/signup/', signup_forum, name="signup"),
    path('<str:slug_forum>/<int:pk_forum>/index/', index, name="index"),
    path('<str:slug_forum>/<int:pk_forum>/sub-category/<int:pk>/<str:slug_sub_category>', sub_category_view,
         name="sub-category"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk>/<str:slug_sub_category>/add/', add_topic, name="add-topic"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk>/<str:slug_sub_category>/<int:pk_topic>/<str:slug_topic>/',
         topic_view,
         name="topic"),
    path(
        '<str:slug_forum>/<int:pk_forum>/<int:pk>/<str:slug_sub_category>/<int:pk_topic>/<str:slug_topic>/<int:pk_message>/',
        update_message,
        name="update-message"),
    path('<int:pk_forum>/delete-message/<int:pk_topic>/<int:pk_message>/', delete_message, name="delete-message"),
    path('<int:pk_forum>/<int:pk_message>/like', like_unlike_view, name="like"),
    path('<str:slug_forum>/<int:pk_forum>/private-messaging/', personal_messaging, name="private-messaging"),
    path('<str:slug_forum>/<int:pk_forum>/private-messaging/<str:slug_conversation>/<int:pk_conversation>/',
         conversation_view,
         name="conversation"),
    path('<str:slug_forum>/<int:pk_forum>/start-conversation/<int:pk_member>/', start_conversation,
         name="start-conversation"),
    path(
        '<str:slug_forum>/<int:pk_forum>/update-message/<str:slug_conversation>/<int:pk_conversation>/<int:pk_message>',
        update_message_conversation,
        name="update-message-conversation"),
    path('<int:pk_forum>/delete-message-conversation/<int:pk_conversation>/<int:pk_message>/',
         delete_message_conversation,
         name="delete-message-conversation"),
    path('<str:slug_forum>/<int:pk_forum>/profile/', profile_forum, name="profile"),
    path('<str:slug_forum>/<int:pk_forum>/members-list/', members_list_view, name="members-list"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk_member>/', member_view, name="member"),
    path("<str:slug_forum>/<int:pk_forum>/notifications/", notifications_view, name="alerts"),
    path('<int:pk_forum>/delete-notifications/', delete_notifications, name="delete-alerts"),
    path('<str:slug_forum>/<int:pk_forum>/query', query_view, name="query"),

    # Admin Part
    path('<str:slug_forum>/<int:pk_forum>/admin/index', index_admin_view, name="admin-index"),
    path('<int:pk_forum>/<int:pk_topic>/pin/', pin_topic, name="pin"),
    path('<str:slug_forum>/<int:pk_forum>/admin/members/', display_members, name="admin-members"),
    path('<int:pk_forum>/<int:pk_member>/admin/member-status/', member_status_view, name="admin-member-status"),
    path('<str:slug_forum>/<int:pk_forum>/admin/builder/', builder_view, name="builder"),
    path('<int:pk_forum>/<int:pk_category>/admin/delete-category/', delete_category_view, name="delete-category-admin"),
    path('<int:pk_forum>/<int:pk_subcategory>/admin/delete-subcategory/', delete_subcategory_view,
         name="delete-subcategory-admin"),
    path('<str:slug_forum>/<int:pk_forum>/admin/update-category/<int:pk_category>/', update_category_view,
         name="admin-update-category"),
    path('<str:slug_forum>/<int:pk_forum>/admin/update-subcategory/<int:pk_subcategory>/', update_subcategory_view,
         name="admin-update-subcategory"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk_category>/admin/add-subcategory/', add_sub_category,
         name="admin-add-sub-category"),
    path('<str:slug_forum>/<int:pk_forum>/admin/update-topic/<int:pk_topic>/', update_topic, name="admin-update-topic"),
    path('<int:pk_forum>/admin/delete-topic/<int:pk_topic>/', delete_topic_view, name="admin-delete-topic"),
]

platforum_project/landing/urls.py
from django.urls import path

from landing.views import index, forums_list_view, my_forums_list_view, forum_documentation_view, \
    admin_documentation_view

app_name = "landing"
urlpatterns = [
    path('', index, name="index"),
    path('forums-list/', forums_list_view, name="forums-list"),
    path('my-forums-list/', my_forums_list_view, name="my-forums-list"),
    path('documentation-forum/', forum_documentation_view, name="documentation-forum"),
    path('admin-documentation/', admin_documentation_view, name="admin-documentation"),
]

platforum_project/platforum_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('account/', include('account.urls')),
    path('forum/', include('forum.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sav/', include('sav.urls')),
]

if settings.ENV != "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platforum_project/sav/urls.py
from django.urls import path
from .views import contact_view, legal_view


app_name = "sav"
urlpatterns = [
    path('contact/', contact_view, name="contact"),
    path('legal/', legal_view, name="legal")
    ]

platforum_project/templates/base_forum.html
{% load static %}
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg shadow mb-5" style="background-color: rgba(25, 135, 84, 0.30);">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'landing:index' %}">
            <img src="{% static 'assets/logo.png' %}" alt="Bootstrap" width="40">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'landing:index' %}">Accueil
                        PyForum</a>
                </li>
                <!-- Penser à la condition pour faire en sorte que l'utilisateur appartienne au forum... ou non -->
                {% if account %}
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'forum:profile' pk_forum=forum.pk slug_forum=forum.slug %}">Profil</a>
                </li>
                {% if account.active %}
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'forum:private-messaging' slug_forum=forum.slug pk_forum=forum.pk %}">Messagerie privée</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:members-list' slug_forum=forum.slug pk_forum=forum.pk %}">Liste des membres</a>
                </li>
                {% endif %}
                <!-- Ici le else pour qu'il demande accès au forum par exemple -->
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:signup' slug_forum=forum.slug pk_forum=forum.pk %}">Devenir membre de ce forum</a>
                </li>
                {% endif %}

                <!--Admin forum -->
                {% if account %}
                {% if account.forum_master %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Admin Forum
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'forum:admin-index' slug_forum=forum.slug pk_forum=forum.pk %}">Vue d'ensemble</a></li>
                        <li><a class="dropdown-item" href="{% url 'forum:admin-members' slug_forum=forum.slug pk_forum=forum.pk %}">Membres</a></li>
                        <li><a class="dropdown-item" href="{% url 'forum:builder' slug_forum=forum.slug pk_forum=forum.pk %}">Construction</a></li>

                    </ul>
                </li>
                {% endif %}
                {% endif %}

            </ul>
            <form class="d-flex" role="search" action="{% url 'forum:query' slug_forum=forum.slug pk_forum=forum.pk %}">
                <input class="form-control me-2" type="search" placeholder="Rechercher dans le forum" aria-label="Search" name="query" maxlength="100" minlength="3">
                <button class="btn btn-outline-success" type="submit">Rechercher</button>
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid text-center shadow-lg mb-5 rounded p-5">
 <div class="row justify-content-center align-items-center">
        <div class="col-auto">
    <a href="{{ forum.get_absolute_url }}" class="index-link"><h1 class="display-1 p-4">{{ forum.name }}</h1></a><img src="{{ forum.thumbnail_url }}" width="200px" height="auto" class="circle">
    <strong>par</strong>
    <h2><span style="color: rgba(25, 135, 84);">{{ forum.forum_master.username }}</span></h2>
    {% block head %}{% endblock %}
        </div>
        </div>

    {% if account %}
    {% if account.active %}
    <div class="row mb-2">
        <div class="col-3"><a href="{% url 'forum:alerts' slug_forum=forum.slug pk_forum=forum.pk %}"><img
                src="{% static 'assets/notif.png' %}" height="50" width="auto" class="circle"></a><span class="notif-link">{{ account.notification_counter }}</span></div>
    </div>
    {% endif %}
    {% endif %}

</div>


{% block body %}{% endblock %}

<div class="container-fluid text-center mt-auto p-5">
    <footer><p>© 2024 PyForum - Tous droits réservés
        {% if request.user.is_superuser %}
        -
        <a href="{% url 'admin:index' %}">Administration avancée</a> -
        <a href="{% url 'sav:legal' %}" target="_blank">Confidentialité</a>
        {% endif %}</p></footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

platforum_project/templates/base_site.html
{% load static %}
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg shadow mb-5" style="background-color: rgba(25, 135, 84, 0.30);">
    <div class="container-fluid">


        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'landing:index' %}">Accueil
                        PyForum</a>
                </li>


                <li class="nav-item">
                    <a class="nav-link" href="{% url 'landing:forums-list' %}">Voir les forums</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:create-forum' %}">Créer son forum</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sav:contact' %}">Contact</a>
                </li>

            </ul>


            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        <img src="{% static 'assets/account.png' %}" width="40" height="auto" class="circle">
                    </a>
                    <ul class="dropdown-menu">
                        {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:signup' %}">S'inscrire</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:login' %}">Connexion</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:logout' %}">Déconnexion</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'account:profile' %}">Mon profil</a></li>
                        <li><a class="dropdown-item" href="{% url 'landing:my-forums-list' %}">Mes forums</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'forum:create-forum' %}">Créer un forum</a></li>
                        {% endif %}
                    </ul>
                </li>

            </ul>


            <form class="d-flex" role="search" action="{% url 'landing:forums-list' %}">
                <input class="form-control me-2" type="search" placeholder="Rechercher un forum"
                       aria-label="Rechercher un forum" name="rechercher-forum" maxlength="100" minlength="3">
                <button class="btn btn-outline-success" type="submit">Rechercher</button>
            </form>


        </div>

    </div>

</nav>

<div class="container-fluid text-center shadow-lg mb-5 rounded p-2">
    <div class="row justify-content-center align-items-center">
        <div class="col-auto">
            <h1 class="display-1 p-4">Py<span style="color: rgba(25, 135, 84);">Forum</span></h1>
        </div>
        <div class="col-auto">
            <img src="{% static 'assets/header.png' %}" width="200px" height="auto" class="circle">
        </div>

    </div>
</div>


{% block body %}{% endblock %}

<div class="container-fluid text-center mt-auto p-5">
    <footer><p>© 2024 PyForum - Tous droits réservés
        {% if request.user.is_superuser %}
        -
        <a href="{% url 'admin:index' %}">Administration avancée</a> -
        <a href="{% url 'sav:legal' %}" target="_blank">Confidentialité</a>
        {% endif %}</p></footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</body>
</html>