platforum_project/forum/urls.py
from django.urls import path
from .views import create_forum, index, sub_category_view, add_topic, topic_view, update_message, delete_message, \
    personal_messaging, conversation_view, update_message_conversation, delete_message_conversation, profile_forum, \
    signup_forum, members_list_view, pin_topic, display_members, member_status_view, member_view, builder_view, \
    delete_category_view, delete_subcategory_view, update_category_view, update_subcategory_view, start_conversation, \
    index_admin_view, notifications_view, delete_notifications, update_topic, delete_topic_view, query_view, \
    add_sub_category, like_unlike_view

app_name = "forum"
urlpatterns = [
    path('create-forum/', create_forum, name="create-forum"),
    path('<str:slug_forum>/<int:pk_forum>/signup/', signup_forum, name="signup"),
    path('<str:slug_forum>/<int:pk_forum>/index/', index, name="index"),
    path('<str:slug_forum>/<int:pk_forum>/sub-category/<int:pk>/<str:slug_sub_category>', sub_category_view,
         name="sub-category"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk>/<str:slug_sub_category>/add/', add_topic, name="add-topic"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk>/<str:slug_sub_category>/<int:pk_topic>/<str:slug_topic>/',
         topic_view,
         name="topic"),
    path(
        '<str:slug_forum>/<int:pk_forum>/<int:pk>/<str:slug_sub_category>/<int:pk_topic>/<str:slug_topic>/<int:pk_message>/',
        update_message,
        name="update-message"),
    path('<int:pk_forum>/delete-message/<int:pk_topic>/<int:pk_message>/', delete_message, name="delete-message"),
    path('<int:pk_forum>/<int:pk_message>/like', like_unlike_view, name="like"),
    path('<str:slug_forum>/<int:pk_forum>/private-messaging/', personal_messaging, name="private-messaging"),
    path('<str:slug_forum>/<int:pk_forum>/private-messaging/<str:slug_conversation>/<int:pk_conversation>/',
         conversation_view,
         name="conversation"),
    path('<str:slug_forum>/<int:pk_forum>/start-conversation/<int:pk_member>/', start_conversation,
         name="start-conversation"),
    path(
        '<str:slug_forum>/<int:pk_forum>/update-message/<str:slug_conversation>/<int:pk_conversation>/<int:pk_message>',
        update_message_conversation,
        name="update-message-conversation"),
    path('<int:pk_forum>/delete-message-conversation/<int:pk_conversation>/<int:pk_message>/',
         delete_message_conversation,
         name="delete-message-conversation"),
    path('<str:slug_forum>/<int:pk_forum>/profile/', profile_forum, name="profile"),
    path('<str:slug_forum>/<int:pk_forum>/members-list/', members_list_view, name="members-list"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk_member>/', member_view, name="member"),
    path("<str:slug_forum>/<int:pk_forum>/notifications/", notifications_view, name="alerts"),
    path('<int:pk_forum>/delete-notifications/', delete_notifications, name="delete-alerts"),
    path('<str:slug_forum>/<int:pk_forum>/query', query_view, name="query"),

    # Admin Part
    path('<str:slug_forum>/<int:pk_forum>/admin/index', index_admin_view, name="admin-index"),
    path('<int:pk_forum>/<int:pk_topic>/pin/', pin_topic, name="pin"),
    path('<str:slug_forum>/<int:pk_forum>/admin/members/', display_members, name="admin-members"),
    path('<int:pk_forum>/<int:pk_member>/admin/member-status/', member_status_view, name="admin-member-status"),
    path('<str:slug_forum>/<int:pk_forum>/admin/builder/', builder_view, name="builder"),
    path('<int:pk_forum>/<int:pk_category>/admin/delete-category/', delete_category_view, name="delete-category-admin"),
    path('<int:pk_forum>/<int:pk_subcategory>/admin/delete-subcategory/', delete_subcategory_view,
         name="delete-subcategory-admin"),
    path('<str:slug_forum>/<int:pk_forum>/admin/update-category/<int:pk_category>/', update_category_view,
         name="admin-update-category"),
    path('<str:slug_forum>/<int:pk_forum>/admin/update-subcategory/<int:pk_subcategory>/', update_subcategory_view,
         name="admin-update-subcategory"),
    path('<str:slug_forum>/<int:pk_forum>/<int:pk_category>/admin/add-subcategory/', add_sub_category,
         name="admin-add-sub-category"),
    path('<str:slug_forum>/<int:pk_forum>/admin/update-topic/<int:pk_topic>/', update_topic, name="admin-update-topic"),
    path('<int:pk_forum>/admin/delete-topic/<int:pk_topic>/', delete_topic_view, name="admin-delete-topic"),
]

platforum_project/platforum_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('account/', include('account.urls')),
    path('forum/', include('forum.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sav/', include('sav.urls')),
]

if settings.ENV != "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platforum_project/sav/urls.py
from django.urls import path
from .views import contact_view, legal_view


app_name = "sav"
urlpatterns = [
    path('contact/', contact_view, name="contact"),
    path('legal/', legal_view, name="legal")
    ]

platforum_project/forum/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .forms import CreateForumForm
from .default_data.default_forum_data import create_forum_with_data


@login_required
def create_forum(request):
    user = request.user
    if request.method == "POST":
        form = CreateForumForm(request.POST)
        if form.is_valid():
            create_forum_with_data(form, user)

    form = CreateForumForm()
    return render(request, "forum/create-forum.html", context={"form": form})

platforum_project/forum/views/admin.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.forms import model_to_dict
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from account.models import CustomUser
from forum.forms import CreateCategory, CategoryForm, SubCategoryForm, ForumUpdateThumbnail, TopicUpdateForm, \
    NewSubCategoryForm
from forum.models import Forum, Topic, ForumAccount, Category, SubCategory, Message
from platforum_project.func.security import verify_forum_master_status


@login_required
def index_admin_view(request, slug_forum, pk_forum):
    """
        Displays the admin view for a specific forum.

        This view function is accessible only to administrators of the forum. It retrieves the forum based on the provided
        primary key and slug. It checks if the logged-in user has an associated forum account and verifies their forum
        master status. The function gathers data about active and banned members, topics, and messages of the forum. If
        a POST request is made, it allows for updating the forum's thumbnail. The gathered data is then passed to the
        admin forum template for rendering.

        Args:
            request: The HTTP request object.
            slug_forum: The slug of the forum (unused in the function but required for URL pattern).
            pk_forum: The primary key of the forum.

        Returns:
            HttpResponse: Renders the admin forum page with context data including the forum, account, form for thumbnail
            update, and lists of active members, banned members, topics, and messages.
        """
    user: CustomUser = request.user
    forum = get_object_or_404(Forum, pk=pk_forum)
    account = user.retrieve_forum_account(forum)
    verify_forum_master_status(account)

    active_members = ForumAccount.objects.filter(forum=forum, active=True)
    ban_members = ForumAccount.objects.filter(forum=forum, active=False)
    topics = Topic.objects.filter(sub_category__category__forum=forum)
    messages = Message.objects.filter(topic__sub_category__category__forum=forum)

    if request.method == "POST":
        form = ForumUpdateThumbnail(request.POST, request.FILES, instance=forum)
        if form.is_valid():
            form.save()
            redirect(request.path)
    else:
        form = ForumUpdateThumbnail()
    return render(request, "admin-forum/index.html", context={"forum": forum, "account": account, "form": form,
                                                              "active_members": active_members,
                                                              "ban_members": ban_members, "topics": topics,
                                                              "messages": messages})


@login_required
@require_POST
def pin_topic(request, pk_forum, pk_topic):
    """
        Handles the pinning or unpinning of a topic within a forum.

        Accessible only to users with forum master status, this view toggles the pinned status of a specified topic.
        It first verifies the user's association with the forum and their authority to pin or unpin topics. If the
        topic is currently unpinned, it gets pinned, and vice versa. The function then redirects to the sub-category
        page of the topic.

        Args:
            request: The HTTP request object.
            pk_forum: The primary key of the forum.
            pk_topic: The primary key of the topic to be pinned or unpinned.

        Returns:
            HttpResponse: Redirects to the sub-category page of the topic after toggling its pinned status.
        """
    user: CustomUser = request.user
    forum = get_object_or_404(Forum, pk=pk_forum)
    account = user.retrieve_forum_account(forum)
    topic = get_object_or_404(Topic, pk=pk_topic)
    verify_forum_master_status(account)
    topic.pin_topic() if not topic.pin else topic.unpin_topic()
    return redirect("forum:sub-category", slug_forum=forum.slug, pk_forum=forum.pk,
                    pk=topic.sub_category.pk, slug_sub_category=topic.sub_category.slug)


@login_required
def display_members(request, slug_forum, pk_forum):
    """
        Displays the member list for a specific forum.

        This view, intended for forum administrators, retrieves and displays a list of members of a specific forum. It
        checks the requesting user's forum account and their forum master status. The function also provides a search
        functionality to filter members by username. The list of members excludes forum masters.

        Args:
            request: The HTTP request object, potentially containing a search query.
            slug_forum: The slug of the forum (unused in the function but required for URL pattern).
            pk_forum: The primary key of the forum.

        Returns:
            HttpResponse: Renders the forum members page with context data including the forum, the user's forum account,
            and the list of members (filtered by search query if provided).
        """
    user: CustomUser = request.user
    forum = get_object_or_404(Forum, pk=pk_forum)
    account = user.retrieve_forum_account(forum)
    verify_forum_master_status(account)
    members = ForumAccount.objects.filter(forum=forum, forum_master=False)

    search = request.GET.get("search")
    if search:
        members = ForumAccount.objects.filter(forum=forum, forum_master=False, user__username__icontains=search)
    return render(request, "admin-forum/members.html", context={"forum": forum, "account": account, "members": members})


@login_required
@require_POST
def member_status_view(request, pk_forum, pk_member):
    """
       Toggles the active status of a forum member.

       This view function, restricted to forum masters, allows toggling the active status (active or banned) of a
       forum member. It first verifies the authority of the requesting user in the forum. The function prevents
       altering the status of forum masters. After changing the member's status, it redirects to either the individual
       member view or the forum's admin members list, based on the POST request data.

       Args:
           request: The HTTP POST request object.
           pk_forum: The primary key of the forum.
           pk_member: The primary key of the member whose status is to be toggled.

       Returns:
           HttpResponse: Redirects to either the individual member view or the forum's admin members list.

       Raises:
           PermissionDenied: If the target member is a forum master.
       """
    user: CustomUser = request.user
    forum = get_object_or_404(Forum, pk=pk_forum)
    verify_forum_master_status(account=user.retrieve_forum_account(forum))
    member_account: ForumAccount = get_object_or_404(ForumAccount, pk=pk_member)
    if member_account.forum_master:
        raise PermissionDenied()
    member_account.deactivate() if member_account.active else member_account.activate()

    if request.POST.get("redirect") == "member-view":
        return redirect("forum:member", slug_forum=forum.slug, pk_forum=forum.pk, pk_member=member_account.pk)
    return redirect("forum:admin-members", slug_forum=forum.slug, pk_forum=forum.pk)


@login_required
def builder_view(request, slug_forum, pk_forum):
    """
       Handles the creation of categories and sub-categories within a forum.

       This view is accessible only to forum masters. It displays existing categories and provides a form to create new
       categories and up to five sub-categories. The form data is used to create new Category and SubCategory objects
       associated with the forum. After creation, it redirects to the same page to allow further creation.

       Args:
           request: The HTTP request object, either GET for displaying the form or POST for submitting the form.
           slug_forum: The slug of the forum (unused in the function but required for URL pattern).
           pk_forum: The primary key of the forum.

       Returns:
           HttpResponse: Renders the forum builder page with context data including the forum, user's forum account,
           existing categories, and the category creation form.
       """
    user: CustomUser = request.user
    forum = get_object_or_404(Forum, pk=pk_forum)
    account = user.retrieve_forum_account(forum)
    verify_forum_master_status(account)
    categories = Category.objects.filter(forum=forum)

    if request.method == "POST":
        form = CreateCategory(request.POST)
        if form.is_valid():
            category = Category.objects.create(name=form.cleaned_data["category"], forum=forum,
                                               index=form.cleaned_data["index_category"])
            for i in range(1, 6):
                sub_category_name = form.cleaned_data[f"sub_{i}"]
                if sub_category_name:
                    SubCategory.objects.create(name=sub_category_name, category=category,
                                               index=form.cleaned_data[f"index_{i}"])
            return redirect(request.path)
    else:
        form = CreateCategory()
    return render(request, "admin-forum/builder.html", context={"forum": forum,
                                                                "account": account,
                                                                "categories": categories,
                                                                "form": form})


@login_required
def add_sub_category(request, slug_forum, pk_forum, pk_category):
    """
        Handles the addition of a new sub-category to a specific category in a forum.

        This view is accessible only to forum masters. It provides a form to create a new sub-category within a given
        category of the forum. Upon POST request with valid form data, it creates and saves the new sub-category

platforum_project/forum/views/creation.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from forum.forms import CreateForumForm
from forum.default_data.default_forum_data import create_forum_with_data


@login_required
def create_forum(request):
    """
        Handles the creation of a new forum.

        This view, accessible only to logged-in users, provides a form for creating a new forum. Upon submission of the
        form with valid data (POST request), a new forum is created using the 'create_forum_with_data' function with the
        logged-in user as the forum master. The user is then redirected to the newly created forum. If accessed via a GET
        request, the form for creating a new forum is displayed.

        Args:
            request: The HTTP request object, either GET for displaying the form or POST for submitting form data.

        Returns:
            HttpResponse: Renders the forum creation page with the form or redirects to the new forum's page after creation.
        """
    user = request.user
    if request.method == "POST":
        form = CreateForumForm(request.POST, request.FILES)
        if form.is_valid():
            forum = create_forum_with_data(form, user)
            return redirect("forum:index", slug_forum=forum.slug, pk_forum=forum.pk)
    else:
        form = CreateForumForm()
    return render(request, "creation/create-forum.html", context={"form": form})

platforum_project/forum/templates/private/conversation.html
{% extends "base_forum.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}{{ conversation.subject }}{% endblock %}

{% block body %}

<div class="container p-5 mb-4">
    <div class="row justify-content-between">
        <div class="col-sm-12 col-md-4 shadow-lg mb-2">
            <h2>Conversation</h2>
            <h3 style="color: green;">{{ conversation.subject }}</h3>
            <a href="{% url 'forum:private-messaging' slug_forum=forum.slug pk_forum=forum.pk %}"><img src="{% static 'assets/return.png' %}" height="40" width="auto"></a>
        </div>
        <div class="col-md-4 col-sm-12 shadow-lg">
            <p><strong>Initiée par</strong> <span style="color: red;">{{ conversation.account.user.username }}</span></p>
            <p><strong>Avec</strong> {% for contact in contacts %}<span style="color: blue;">{{ contact.user.username }}</span> {% endfor %}</p>
        </div>
    </div>

</div>


<div class="container rounded p-5 mb-5 border shadow-lg">

    {% for message in page_obj %}


    <div class="card text-center shadow-lg mb-3">
        <div class="card-header" style="background-color: rgba(136, 204, 136);">
            Par {{ message.account.user.username }} <img class="rounded" src="{{ message.account.thumbnail_url }}" height="50"
                                                 width="auto">
        </div>
        <div class="card-body">
            <div class="d-flex justify-content-end">
                {% if request.user == message.account.user %}
                <a data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Modifier"
                   href="{% url 'forum:update-message-conversation' slug_forum=forum.slug pk_forum=forum.pk slug_conversation=conversation.slug pk_conversation=conversation.pk pk_message=message.pk %}"><img
                        class="rounded" src="{% static 'assets/update.png' %}" height="40" width="auto"></a>

                <!-- Button trigger modal -->
                <button type="button" class="btn-close" data-bs-toggle="modal"
                        data-bs-target="#deletemodal{{ message.pk }}">
                </button>

                <!-- Modal -->
                <div class="modal fade" id="deletemodal{{ message.pk }}" tabindex="-1"
                     aria-labelledby="Delete{{ message.pk }}"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="Delete{{ message.pk }}">Supprimer le message</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Cette action est irréversible
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-success" data-bs-dismiss="modal">Retour</button>
                                <form method="post" action="{% url 'forum:delete-message-conversation' pk_forum=forum.pk pk_conversation=conversation.pk pk_message=message.pk %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Confirmer</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Enf of Modal -->

                {% endif %}
            </div>
            {{ message.message|safe }}

        </div>
        <div class="card-footer text-body-secondary">
            Le {{ message.creation }}
            {% if message.update_counter > 0 %}
            <i>Modifié le {{ message.update }}</i>
            {% endif %}
        </div>
    </div>
    {% endfor %}
        <!-- Pagination -->
    <div class="row mt-5">

         <nav aria-label="Page navigation example">
  <ul class="pagination">

        {% if page_obj.has_previous %}
      <li><a href="?page=1" class="page-link">&laquo; Début</a></li>
      <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Précédent</a></li>
        {% endif %}


        {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}" class="page-link">Suivant</a></li>
      <li> <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">Fin &raquo;</a></li>
        {% endif %}

  </ul>
</nav>
        <strong>Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.</strong>


    </div>
</div>
<!-- Le formulaire pour répondre -->
<div class="container rounded p-5 mb-5 border shadow-lg">

    <div class="row">
        <div class="col-12 text-center">
            <h3>Répondre à la conversation : <span style="color: rgba(25, 135, 84);">{{ conversation.subject }}</span>
            </h3>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-12">
            <form method="post">
                {% csrf_token %}
                {{ form.media }}
                <div class="text-center">
                    {{ form|crispy }}

                    <input type="submit" value="Soumettre" class="btn btn-success">
                </div>
            </form>
        </div>

    </div>
    <div class="row" style="color: red;">
        {% if form.errors %}

        {{ form.errors }}

        {% endif %}

    </div>

</div>

{% endblock %}

platforum_project/forum/templates/private/notifications.html
{% extends "base_forum.html" %}
{% load static %}

{% block title %}Notifications {{ account.user.username }}{% endblock %}

{% block body %}

<div class="container shadow-lg rounded border p-5">
    <div class="row mb-2">
        <div class="col-3"><a href="{% url 'forum:index' slug_forum=forum.slug pk_forum=forum.pk %}"><img
                src="{% static 'assets/return.png' %}" height="40" width="auto"></a></div>
    </div>
    <div class="row text-center">
        <h2 class="mb-5">Notifications</h2>
    </div>


    <div class="row text-center">
        <div class="col">
            {% if notifications %}
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Notification</th>
                </tr>
                </thead>
                {% for notification in notifications %}
                <tbody>
                <tr>

                    <td>{{ notification.message }}</td>
                </tr>
                </tbody>
                {% endfor %}
            </table>
            <form method="post" action="{% url 'forum:delete-alerts' pk_forum=forum.pk %}">
                {% csrf_token %}
                <input type="submit" value="Supprimer les notifications" class="btn btn-danger">

            </form>
            {% else %}
            <h3>Vous n'avez pas encore de notifications</h3>
            {% endif %}

        </div>


    </div>

</div>


{% endblock %}

platforum_project/forum/templates/private/personal-messaging.html
{% extends "base_forum.html" %}
{% load static %}

{% block title %}Boite personnelle {{ request.user }}{% endblock %}

{% block body %}


<div class="container rounded p-5 mb-5">
    <div class="row mb-2"><div class="col-3"><a href="{% url 'forum:index' slug_forum=forum.slug pk_forum=forum.pk %}"><img src="{% static 'assets/return.png' %}" height="40" width="auto"></a></div> </div>

    <div class="row mb-2" style="color: rgba(25, 135, 84);"><h4>Conversation(s) initiée(s)</h4></div>
    <div class="row mb-2">
        <div class="col-3"><a
                href="{% url 'forum:members-list' slug_forum=forum.pk pk_forum=forum.pk %}"
                class="btn btn-success">Nouvelle conversation</a></div>
    </div>

    <!-- Sujets épinglés -->
    {% if my_conversations %}
    <div class="card text-center shadow-lg mb-5">
        <div class="card-header row fw-bold mx-0" style="background-color: rgba(255, 218, 185, 1);">
            <div class="col-6">Sujets</div>
            <div class="col-6">Dernier message</div>


        </div>

        {% for my_conversation in my_conversations %}

        <div class="row border-bottom p-2 mx-0">
            <div class="justify-content-between d-flex">
                <div class="col-6"><a class="topic-link"
                                      href="{% url 'forum:conversation' slug_forum=forum.slug pk_forum=forum.pk slug_conversation=my_conversation.slug pk_conversation=my_conversation.pk %}">{{ my_conversation.subject }}</a>
                    <br><span class="badge bg-secondary">Messages : {{ my_conversation.number_of_messages }}</span>
                </div>

                <div class="col-6">{{ my_conversation.last_message }}</div>

            </div>
        </div>

        {% endfor %}


    </div>
    {% endif %}
    <div class="row mb-2" style="color: rgba(25, 135, 84);"><h4>Autre(s) conversation(s)</h4></div>
    {% if conversations %}
    <!-- Sujets -->
    <div class="card text-center shadow-lg">
        <div class="card-header row fw-bold mx-0" style="background-color: rgba(136, 204, 136);">
            <div class="col-6">Sujets</div>
            <div class="col-6">Dernier message</div>


        </div>

        {% for conversation in conversations %}

        <div class="row border-bottom p-2 mx-0">
            <div class="justify-content-between d-flex">
                <div class="col-6"><a class="topic-link"
                                      href="{% url 'forum:conversation' slug_forum=forum.slug pk_forum=forum.pk slug_conversation=conversation.slug pk_conversation=conversation.pk %}">{{ conversation.subject }}</a>
                <br><span class="badge bg-secondary">Messages : {{ conversation.number_of_messages }}</span></div>
                <div class="col-6">{{ conversation.last_message }}</div>

            </div>
        </div>

        {% endfor %}


    </div>
{% endif %}
</div>

{% endblock %}

platforum_project/forum/templates/private/profile.html
{% extends "base_forum.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Profil de {{ account.user.username }}{% endblock %}

{% block body %}


<div class="container shadow-lg rounded border p-5 mb-5">
    <div class="row mb-2">
        <div class="col-3"><a href="{% url 'forum:index' slug_forum=forum.slug pk_forum=forum.pk %}"><img
                src="{% static 'assets/return.png' %}" height="40" width="auto"></a></div>
    </div>
    <div class="row text-center justify-content-center">
        <div class="col-6">
            <h2 class="mb-2">Compte de <span style="color: rgba(25, 135, 84);">{{ account.user.username }}</span></h2>
            <h5 class="mb-2">A rejoint le forum le <span style="color: blue;">{{ account.joined }}</span></h5>
            <h5 class="mb-5">Approuvé <span style="color: red;">{{ account.likes }}</span> fois</h5>
            <img src="{{ account.thumbnail_url }}" width="100" height="auto" class="mb-5 circle">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Modifier" class="btn btn-success">
            </form>
        </div>
    </div>


</div>


<div class="container shadow-lg rounded border p-5 mb-5">
    <div class="row text-center justify-content-center">
        <h2>Badges</h2>
        <div class="col-6 justify-content-center d-flex">
            {% if account.badges %}
            {% for badge in account.badges.all %}
            <div data-bs-toggle="tooltip" data-bs-placement="top"
                    data-bs-title="{{ badge.description }}">
                <img src="{{ badge.thumbnail.url }}" width="80" height="auto" class="mb-5 circle">
            </div>

            {% endfor %}
            {% endif %}
        </div>

    </div>
</div>


<div class="container shadow-lg rounded border p-5 mb-5">
    <div class="row text-center justify-content-center">
        <h2>Vos dernières contributions</h2>
        <div class="col-6">
            {% if messages %}
            <div class="list-group">
                {% for message in messages %}
                <a href="{% url 'forum:topic' slug_forum=forum.slug pk_forum=forum.pk pk=message.topic.sub_category.pk slug_sub_category=message.topic.sub_category.slug pk_topic=message.topic.pk slug_topic=message.topic.slug %}"
                   class="list-group-item list-group-item-action list-group-item-success">Dans {{ message.topic.title }}
                    le {{ message.creation }}</a>
                {% endfor %}
            </div>
            {% else %}
            <h6>Vous n'avez pas encore posté de message</h6>
            {% endif %}
        </div>

    </div>
</div>

{% endblock %}

platforum_project/forum/templates/private/start-conversation.html
{% extends "base_forum.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Commencer une conversation avec {{ member.user.username }}{% endblock %}

{% block body %}

<!-- Le formulaire pour répondre -->
<div class="container rounded p-5 mb-5 border shadow-lg">
    <div class="row">
        <a href="{% url 'forum:private-messaging' slug_forum=forum.slug pk_forum=forum.pk %}"><img src="{% static 'assets/return.png' %}" height="40" width="auto"></a>
    </div>

    <div class="row">
        <div class="col-12 text-center">
            <h3>Commencer une conversation avec : <span style="color: rgba(25, 135, 84);">{{ member.user.username }}</span>
            </h3>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-12">
            <form method="post">
                {% csrf_token %}
                {{ form.media }}
                <div class="text-center">
                    {{ form|crispy }}

                    <input type="submit" value="Soumettre" class="btn btn-success">
                </div>
            </form>
        </div>

    </div>
    <div class="row" style="color: red;">
        {% if form.errors %}

        {{ form.errors }}

        {% endif %}

    </div>

</div>

{% endblock %}